# Generated by Django 3.2.14 on 2022-08-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('codeforces', models.CharField(max_length=1)),
                ('atcoder', models.CharField(max_length=1)),
                ('codechef', models.CharField(max_length=1)),
            ],
        ),
    ]
