# Generated by Django 3.2.14 on 2022-08-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='datesignup',
            field=models.CharField(default=2020, max_length=20),
            preserve_default=False,
        ),
    ]
